version: 0.0
os: linux
files:
  - source: ./deploy.sh
    destination: /home/ubuntu/app
  - source: ./docker-compose.yml
    destination: /home/ubuntu/app

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 600
      runas: ubuntu
