version: '3.8'

services:
  blue:
    image: myapp:${TAG}
    container_name: blue
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  green:
    image: myapp:${TAG}
    container_name: green
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
