version: "3.8"

services:
  app:
    image: seonghooni0327/myapp:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
