version: '3.8'

services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blue
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: always

  green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: always