name: "FE SUB-ISSUE"
description: 프론트엔드 작업용 서브 이슈 작성 양식입니다.
labels: ["Part: 🌐 FE"]
title: "[FE] [SUB] {도메인} > {작업내용}"
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[FE] [SUB] Login > 소셜 로그인 버튼 생성"
  - type: textarea
    id: feature-description
    attributes:
      label: 작업 설명
      description: 어떠한 기능을 추가하시는 건지 적어주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: 접근 방법
      description: 고려하신 방법이나, 접근에 대해서 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
