name: "MAIN ISSUE"
description: 메인 이슈 작성 양식입니다.
title: "[FE/BE] [MAIN] {도메인} > {작업내용}"
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[BE] [MAIN] Auth: 소셜 로그인 기능 구현"
  - type: textarea
    id: feature-description
    attributes:
      label: 작업 설명
      description: 어떠한 기능을 추가하시는 건지 적어주세요. 필요한 SUB-ISSUE가 있다면 함께 작성해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
