spring:
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 600000        # 10분 (기본)
      max-lifetime: 1800000       # 30분 (DB wait_timeout보다 짧게)
      connection-timeout: 30000   # 커넥션 획득 대기 30초
      leak-detection-threshold: 20000 # 20초 이상 반환 안되면 로그 경고
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: health, mappings


  metrics:
    tags:
      application: app
    export:
      cloudwatch:
        enabled: true
        namespace: "SpringApp-JVM"
        step: 60s
        region: ap-northeast-2
    enable:
      all: false
      jvm: true
      process: true
      system: true