spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  data:
    redis:
      repositories:
        enabled: false
      timeout: 3s

server:
  servlet:
    session:
      cookie:
        secure: true         # HTTPS 필수
        same-site: none      # none, lax, strict

springdoc:
  api-docs:
    enabled: true                   # API 문서(`/v3/api-docs`) 활성화 여부
    path: /v3/api-docs              # API 문서 엔드포인트
    groups:
      enabled: true                 # API 그룹 지원 여부

  swagger-ui:
    enabled: true                   # Swagger UI 활성화
    path: /swagger-ui.html          # 접속 경로
    operationsSorter: method        # API 정렬 기준
    tagsSorter: alpha               # 태그 정렬 기준
    display-request-duration: true  # 실행시간이 UI에 표시
    doc-expansion: none             # 설명 펼침 여부 반영
    persistAuthorization: true      # 새로고침 후 인증 유지 여부 반영
    defaultModelsExpandDepth: -1    # 모델 깊이 반영됨

  paths-to-match:
    - /api/**

  cache:
    disabled: true

  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: health

aws:
  s3:
    bucket: todoc-s3-bucket
    region: ap-northeast-2
    uploads-prefix: uploads/
    # 아래 두 값은 로컬스택/미니오 쓸 때만 사용 (실AWS면 빼거나 주석)
    # endpoint: http://localhost:4566
    # path-style-access: true

upload:
  presign:
    put-expire-seconds: 600   # 업로드 URL 유효기간(초)
    get-expire-seconds: 600   # 다운로드 URL 유효기간(초)

tmap:
  app-key: ${TMAP_API_KEY:}