spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    url: ${DB_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

