spring:
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web.exposure.include: health,metrics,info
  metrics:
    tags:
      application: app              # 대시보드에서 식별용 공통 태그
    export:
      cloudwatch:
        enabled: true
        namespace: "SpringApp-JVM"            # CloudWatch 네임스페이스
        step: 60s                   # 전송 주기
    enable:                         # 과다 지표 방지(필요한 것만)
      all: false
      jvm: true
      process: true
      system: true