name: Backend CI Test to develop

on:
  pull_request:
    branches:
      - develop
    paths:
      - "backend/**"

env:
  SPRING_PROFILE: ci
  DB_URL: jdbc:mysql://localhost:3306/todoc_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  DB_USERNAME: testuser
  DB_PASSWORD: testpass

jobs:
  validate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: todoc_db
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -prootpass || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=30
          --health-start-period=20s

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: |
          cd backend/server
          ./gradlew clean build

      - name: Run application in background
        run: |
          nohup java -Dspring.profiles.active=${SPRING_PROFILE} -jar backend/server/build/libs/server-0.0.1-SNAPSHOT.jar &
          echo $! > app.pid
          sleep 15

      - name: Check application health
        run: |
          curl -f http://localhost:8080/actuator/health

      - name: Stop application
        run: |
          kill -9 $(cat app.pid)
